# Generated by Django 2.2.4 on 2019-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atlus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='predicts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='predict',
        ),
    ]
