# Generated by Django 2.2.4 on 2019-12-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_predict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='predict',
        ),
    ]
